### ISSUE TITLE
[BUG] Download button styling issue

### ISSUE THREAD

**Issue by sdlawrence** [EltonChou/TwitterMediaHarvest#120]
In Firefox 119.0.1 (64-bit, Windows 10), the Twitter Downloader Icon is now masking the Reply, Like, and Share icons such that when any are clicked, it selects the Download button instead. 

![image](https://github.com/EltonChou/TwitterMediaHarvest/assets/417105/97ebc12e-da43-4be4-a0da-2dd997aaf791)

**Comment by sdlawrence** [comment]
I didn't realize an update was available. Apologies for the bug assignment without updating to the latest version first (which fixed it for me).  Love this extension, cheers.

**Comment by sdlawrence** [comment]
Closing now, thank you.

**Comment by sdlawrence** [comment]
Spoke too soon, still a problem!

**Comment by EltonChou** [comment]
I think they are testing some UI changes, will check this in a few days if they are stable.

**Comment by Laurens256** [comment]
Maybe unrelated to this but you could add a download button in the extensions popup window which downloads the media from the current url, so that if twitter changes their ui, the button inside the extension window will always be in the same location
![OnPaste 20231124-180637](https://github.com/EltonChou/TwitterMediaHarvest/assets/85798751/f020d2d2-b015-4811-bfff-a5638826b794)
Feel free to do with this what you want

**Comment by EltonChou** [comment]
> Maybe unrelated to this but you could add a download button in the extensions popup window which downloads the media from the current url, so that if twitter changes their ui, the button inside the extension window will always be in the same location ![OnPaste 20231124-180637](https://user-images.githubusercontent.com/85798751/285514114-f020d2d2-b015-4811-bfff-a5638826b794.png) Feel free to do with this what you want

If user want to download media in replies, that would be confused and it was against the one-click principal.
