### ISSUE TITLE
[FEATURE] Download currently open image from multiple image post only.

### ISSUE THREAD

**Issue by timf1256** [EltonChou/TwitterMediaHarvest#132]
Hi, currently if you open an image in the large viewing mode (not sure what it's technically called, it's when you click on the image thumbnail directly) and the post has multiple image files, if you click the download button it downloads all images from the post.

I would prefer if it only downloaded the image you are currently viewing.  If you have the post itself open with all the image thumbnails and click download, it could download them all.

Similarly, if you open an image in the larger viewing mode, there is a sidebar on the right where "Discover more" posts are shown.  If you click on a thumbnail in that sidebar, and then click the download button while viewing that image, it instead downloads the original post's image(s) you had been viewing before clicking on something from the sidebar.  This is confusing and almost seems like a bug to me.

Thanks for your hard work.

**Comment by EltonChou** [comment]
1. Specified download would be a break change.
Donwnload the specified image is good idea, but download one or all consumes same quota.
Most of the users want to grab more medias, but the quota is limited.
Since there are over 20K users right now and a lot of things need to be redesigned for this change,
I don't think I will work on this in the near future.

2. It  is a bug, everything in photo mode would be little tricky.
I will fix this.

**Comment by EltonChou** [comment]
- Requested feature would not be implemented, unless more users request this feature.
- The bug was fixed.
