### ISSUE TITLE
[BUG] Conflict with another Chrome extension

### ISSUE THREAD

**Issue by MGuerrera** [EltonChou/TwitterMediaHarvest#187]
**Describe the bug**
I report a conflict with the "Double-click Image Downloader" extension.
When the latter is installed and active, "Media Harvest" ignores the save location and filename pattern settings: all files are simply saved to the Downloads folder with an alphanumeric name and jpg_orig or png_orig extensions.

**To Reproduce**
1. Go to Chrome Store
2. Install [Double-click Image Downloader](https://chromewebstore.google.com/detail/double-click-image-downlo/bkijmpolkanhdehnlnabfooghjdokakc) extension.
3. Refresh the X page.
4. Try to download a media content.

**Expected behavior**
The file should be downloaded with the chosen filename pattern, in the designated location, with the expected extension.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser: Chrome
 - Chrome Version: 127.0.6533.120 (Official Build) (arm64)
 - "Double-click Image Downloader" Version: 71.2
 - "Media Harvest" Version: 4.2.8 (chrome)

**Additional context**
I've already looked at this [thread](https://github.com/EltonChou/TwitterMediaHarvest/issues/170), which identifies the problem and suggests turning off extensions that use a particular Chrome API.
Thanks to this suggestion I was able to identify the type of conflict and the extension that triggers it, but having needed it, I hope a solution can be found to make them coexist.

**Comment by EltonChou** [comment]
Thanks for your well-formated report.

This a embarrassed issue for extension.
It is a bug for users, because the filename was modified.
But it is not a bug for this extension, because extension has passed correct filename to browser.
The root cause is chromium browser's behavior, the teams decide to do this.
I have tracked this [chromium issue](https://issues.chromium.org/issues/40258993) for few years. 
Unless chromium team decides to change this behavior, it seems like there is no method to prevent this issue.

I will add a notification to let user know the filename might be overwritten by other extension in `v5.0.0`.

(You can try the `Aggressive mode` in options page. It may fix this issue, but it will cause some buggy behaviors to other extension or in some download situations.)

**Comment by erbanku** [comment]
@EltonChou Where is the  `Aggressive mode` option, I cannot find it.

<img width="2560" height="1347" alt="Image" src="https://github.com/user-attachments/assets/866b06c9-4b69-495e-8e34-fc5faa7d43f5" />

> (You can try the Aggressive mode in options page. It may fix this issue, but it will cause some buggy behaviors to other extension or in some download situations.)
