### ISSUE TITLE
Option to not overwrite existing files

### ISSUE THREAD

**Issue by BitRYNO** [EltonChou/TwitterMediaHarvest#68]
The previous version did not overwrite files that already exist in the download directory.  The current version will overwrite any existing files. This can mess with file order especially if file are sorted by date downloaded.

**Comment by EltonChou** [comment]
Can you provide your extension version and browser version?
This extension always overwrite files with same filename.
There must be some bugs If it didn't overwrite it.

Because they are same files, I don't need any duplicated file to consume my space.
If you want the filename with download date you can add `Date` in the filename pattern setting.

**Comment by BitRYNO** [comment]
Chrome Version 113.0.5672.93
Extension Version before the new options interface
Can a feature be added to not re-download files if they already exist in the download folder?

**Comment by EltonChou** [comment]
Please update your extension.

Currently this extension don't have any download history feature.
The permission of extension was restricted by the browser,
and the extension are now allowed to scan the contents in download folder.
It hard to make a reliable `file manager` in an extension.

What's your purpose you want to prevent downloading?
