### ISSUE TITLE
[BUG] Downloads fail outside of logged-in container (Firefox Containers)

### ISSUE THREAD

**Issue by offsetcyan** [EltonChou/TwitterMediaHarvest#99]
**Describe the bug**
If the extension is run from an account logged in via a [Firefox container](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) (official Mozilla extension) Media Harvest tries to download the media from outside of the container context. If the "no container" account isn't logged in, Media Harvest will fail as Twitter's API will reject the request.

**To Reproduce**
1. Create a container and log in to twitter inside that container
2. Make sure "no container" context is not logged in to Twitter
3. Inside that container, try to activate the extension on some Twitter media

**Expected behavior**
Media is downloaded as expected.

**Desktop (please complete the following information):**
 - OS: NixOS 23.05
 - Browser: Firefox 
 - Version: 117.0 (64-bit)

**Comment by EltonChou** [comment]
The addon was loaded in the default container (no container).
If you logout twitter in default container, the addon cannot get useful twitter cookie from backend.
This can be fixed but the whole workflow need to be redesigned.
Since this issue was caused by other extension, I will not do the patch in the near future.

**Comment by EltonChou** [comment]
Firefox suuport was discarded.

**Comment by offsetcyan** [comment]
LOL, why?
